application: thinkjsoncrimson
version: 1
runtime: python27
api_version: 1
threadsafe: true

default_expiration: "5m"

builtins:
- remote_api: on

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"

inbound_services:
- warmup

handlers:
- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /favicon.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon.ico

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /bower_components
  static_dir: bower_components

- url: /js
  static_dir: static/js

- url: /partials
  static_dir: static/partials

- url: /css
  static_dir: static/css

- url: /fonts
  static_dir: static/fonts

- url: /api/.*
  script: application.app

- url: .*
  static_files: static/index.html
  upload: static/index.html